<html>
    
    <?php $num = 1;
    foreach ($view->playerCards as $card){
        $val = $card->getDetails();
        echo "Your Card # $num is $val<br>";
        $num++;
    }?>
    <h3>Your score is 
        <?php echo $view->playerScore; 
        if ($view->playerScore > 21){echo " - Bust!";}?>
    </h3>

    <?php $num = 1;
    foreach ($view->dealerCards as $card){
        $val = $card->getDetails();        
        echo "Dealer's Card # $num is $val<br>";
        $num++;
    }?>
    <h3>Dealer's score is 
        <?php echo $view->dealerScore; 
        if ($view->dealerScore > 21){echo " - Bust!";}?>
    </h3>
    
</html>