<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <title><?php echo $view->pageTitle; ?></title>
        <link href="../css/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../css/style.css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header>
            <img src="images/Facebook-Banner.jpg"
            width="425"
            height="157"
            alt="Salford Computing Society Logo... ffs"
            >
        </header>
